jenkins:
  container_name: 'jenkins'
  build: jenkins/.
  ports:
    - "8080:8080"
  links:
    - sonar:sonar
sonar:
  container_name: 'sonarqube'
  build: sonar/.
  ports:
   - "9000:9000"
   - "5432:5432"
  environment:
   - SONARQUBE_JDBC_URL=jdbc:postgresql://localhost:5432/sonar
db:
  container_name: 'postgres'
  image: postgres
  net: container:sonar
  environment:
   - POSTGRES_USER=sonar
   - POSTGRES_PASSWORD=sonar
artifactory:
  container_name: 'artifactory'
  image: docker.bintray.io/jfrog/artifactory-oss:latest
  ports:
   - "8081:8081"
